### PR TITLE
Added offline json data and fakeweb gem for testing

### LINKED ISSUE #3: Create a file with some JSON in it for testing rather than pulling live data
That way we can test `.empty?` `.full?`, etc. for realz

### PR DESCRIPTION
**Pull request by gabceb**
Added fakeweb gem
Added json with request data to avoid having to query bikeshare every time we run the tests
Fixes #3

### CODE REVIEW

**Comment by zackshapiro** [comment]
How do I check out your branch? It's not showing up for some reason

**Comment by gabceb** [comment]
The commands below should work

```
git checkout -b bikeshare-3
git pull https://github.com/gabceb/bikeshare-1.git bikeshare-3
```

**Comment by zackshapiro** [comment]
Thanks. +1 for making the specs super-fast!

**Comment by zackshapiro** [comment]
Made a commit and it's not showing up here, weird...

**Comment by gabceb** [comment]
I think only commits from my branch will show here unless you merge with master.

**Comment by zackshapiro** [comment]
I should be able to contribute to the branch too, I think...

I'll check it out later tonight

**Comment by gabceb** [comment]
But I may be wrong.... :hushed:

**Comment by gabceb** [comment]
You can use this http://stackoverflow.com/a/11066487/1664346

**Comment by zackshapiro** [comment]
Thanks will check it out shortly 

Best,
Zack

**Pull request merged**
