### PR TITLE
Refactor 

### PR DESCRIPTION
**Pull request by zackshapiro**

### CODE REVIEW

**Comment by zackshapiro** [comment]
@gabceb Made some small style changes to your pull request. 

In `check_valid_station_id!`, was there any particular reason you declared `opts = {}` in the attributes rather than defining and empty hash as the first element of the function. Did you have a specific use case in mind for it?

**Comment by gabceb** [comment]
When I initially wrote the code I thought you were using different exceptions but I guess it was not needed. Doesn't really hurt to have it there just in case.

**Comment by zackshapiro** [comment]
I'd simplify that function so that it only takes a `station_id`, it has two variables `low_station` and `high_station` or something (name them what you want) and then just throws the raise. Doing at all as a hash seems a bit much for what the function needs to do which is check the range and raise if it's not in the range

**Comment by gabceb** [comment]
Ok :+1:

**Comment by zackshapiro** [comment]
Make those changes and I'm happy to merge. Bump the version number in the gemspec file too please :)

**Comment by gabceb** [comment]
My original PR is closed. Do you want me to send you a new PR with your changes or are you going to merge this PR into master?

**Comment by zackshapiro** [comment]
I'll make the changes then. Weird we can't work on a branch in tandem

**Pull request merged**
